### ISSUE TITLE
URL模板

### ISSUE THREAD

**Issue by zli-ray** [DreamHi/HiCrawler#12]
- 添加模板时，URL输入框带默认值：http://
- [+]号按钮是添加参数，但[-]按钮是删除模板，感觉动作不对称。[-]按钮改为[x]如何？
  + [+]按钮添加提示：添加参数
  + [-]按钮添加提示：删除模板
- 点击[+]按钮时
  + 如果焦点在当前模板的URL输入框中时，则在输入光标处插入文本：{参数x}
  + 如果焦点不在当前模板的URL输入框中时，则在URL输入框最后插入文本：{参数x}
  + {参数x}中的x为递增数字，从1开始。插入时，x值不能重复。
  + 下面新追加的参数详细设定中，参数名项目默认值设为：参数x

![image](https://user-images.githubusercontent.com/2460808/60769004-6731d580-a0fd-11e9-84a4-f1a2646bafef.png)

**Comment by sl-say** [comment]
点击[+]按钮时功能，感觉有点多余，过于强迫

**Comment by zli-ray** [comment]
现状的话，用户不知道参数该如何/以什么形式插入到URL中。
要不先简单对应一下吧，如下：

- URL输入框下面添加说明文：请将参数以 {参数名} 的形式插入到网址中
- 参数的【参数名】项目，输入框后面加一个拷贝图标
  + 图标提示文字：拷贝 {参数名} 到粘贴板
  + 点击图标时，将参数名以 {参数名} 的形式拷贝到粘贴板。

**Comment by sl-say** [comment]
那还不如加一个拷贝参数的功能，

**Comment by zli-ray** [comment]
> 那还不如加一个拷贝参数的功能

具体式样是？

**Comment by sl-say** [comment]
类似在删除按钮的区域，加一个拷贝的按钮

**Comment by zli-ray** [comment]
夜色有点晚了，最后一个问题。

> 类似在删除按钮的区域，加一个拷贝的按钮

模板的删除按钮附近，还是参数的删除按钮附近？
【拷贝按钮】点击后，具体动作是？

**Comment by sl-say** [comment]
红色的删除按钮，相当于再追加一个参数。复用当前参数的设定值。
不就是想快速的设定参数吗？

**Comment by zli-ray** [comment]
> 不就是想快速的设定参数吗？

不是。是想方便用户将某个参数插入到URL输入框里，具体明天再说吧。Zzz...

**Comment by zli-ray** [comment]
总结

- 模板追加时
  + URL框里带默认值：http://test/{参数1}
  + 默认添加一个参数，序列型，参数名为“参数1”。
- URL输入框下面添加说明文：请将参数以 {参数名} 的形式插入到网址中
- 参数的【参数名】项目，输入框后面加一个拷贝图标
  + 图标提示文字：拷贝 {参数名} 到粘贴板
  + 点击图标时，将参数名以 {参数名} 的形式拷贝到粘贴板。
