### ISSUE TITLE
日期型参数

### ISSUE THREAD

**Issue by zli-ray** [DreamHi/HiCrawler#16]
- 添加【模式】项目，radio类型，包含【相对日期】和【绝对日期】两个选项，默认为【相对日期】。
- 选中【相对日期】时，【开始日期】和【结束日期】项目变成如下形式（[+]/[-]为下拉框）：
  + ![image](https://user-images.githubusercontent.com/2460808/60813406-42edfb80-a1c6-11e9-82d0-05c9bbd836e1.png)
- 选中【绝对日期】时，【开始日期】和【结束日期】项目变成日期选择控件，可选择年月日。
- 【格式】项目，是可输入的下拉框
  + 下拉框备选值为：yyyyMM，yyyyMMdd
  + 默认值为：yyyyMMdd
- 所有的项目都是必须输入项目

**Comment by sl-say** [comment]
这是什么参数，URL模板？

**Comment by zli-ray** [comment]
是URL模板的日期型参数。之前的相对日期和绝对日期的设定同时显示出来了，分不清楚。
所以加个【模式】项目区分一下。同时，不管是什么模式，项目名都是【开始日期】和【结束日期】。

![image](https://user-images.githubusercontent.com/2460808/60892174-47cbb180-a291-11e9-8e89-cea9c94ec958.png)
