### ISSUE TITLE
UserAgent，备选项IE的版本不明确

### ISSUE THREAD

**Issue by zli-ray** [DreamHi/HiCrawler#7]
- 如下，IE版本不明确，直接写Internet Explorer 11吧。
- IE11的UserAgent是：Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; **rv:11.0**) like Gecko
- firefox和chrome，下拉框中就不需要标记版本了，因为版本差异比较小。

![image](https://user-images.githubusercontent.com/2460808/60754201-56effc80-a010-11e9-81d8-f128d34d9490.png)

**Comment by sl-say** [comment]
firefox和chrome，下拉框中就不需要标记版本了，因为版本差异比较小。
你把具体的值都写下来吧，

**Comment by zli-ray** [comment]
可能意思传达有误，firefox和chrome不需要修改，维持之前的设定即可。

**Comment by zli-ray** [comment]
firefox mac和windows的值跟之前发生变化了。[Firefox/xxx]的部分没有了，误修改？

**Comment by sl-say** [comment]
```js
export const DEF_USER_AGENT = [
  { id: '1', value: 'Mozilla/5.0 Chrome/70.0.3538.77 Safari/537.36', name: 'Chrome Mac' },
  { id: '2', value: 'Mozilla/5.0 Chrome/70.0.3538.77', name: 'Chrome Windows' },
  { id: '3', value: 'Mozilla/5.0 Gecko/20100101', name: 'Firefox Mac' },
  { id: '4', value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64;)', name: 'Firefox Windows' },
  {
    id: '5',
    value: 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko',
    name: 'Internet Explorer 11',
  },
  { id: '6', value: 'Mozilla/5.0 Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134', name: 'Edge' },
];
```

**Comment by zli-ray** [comment]
如下，昨天的更新履历，firefox有变化，修改后看不出来是firefox了。

https://github.com/DreamHi/HiCrawler/commit/399eece080200a5cd16102eb5422311fb6c4f107

**Comment by sl-say** [comment]
哦，忘了，好像改了
