### ISSUE TITLE
代理设定

### ISSUE THREAD

**Issue by zli-ray** [DreamHi/HiCrawler#9]
- 文言修改
  + 代理服务器需要密码 -> 需要认证
- 【用户名/密码】项目默认隐藏，checkbox选中时显示。
- 【用户名/密码】项目与【需要认证】项目对齐

![image](https://user-images.githubusercontent.com/2460808/60754534-e4cde680-a014-11e9-86b4-b840a2811c92.png)

**Comment by sl-say** [comment]
参照mac的系统设定弄的

**Comment by zli-ray** [comment]
用户名和密码两个项目不常用，一直显示的话感觉占地方，画面变长，并且分散注意力。
右对齐显示的话，设定时鼠标移动距离有点大，感觉累。
